//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Isrv112")]
    public interface Isrv112 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isrv112/oper112", ReplyAction="http://tempuri.org/Isrv112/oper112Response")]
        int oper112(float f, long i, string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Isrv112/oper112", ReplyAction="http://tempuri.org/Isrv112/oper112Response")]
        System.Threading.Tasks.Task<int> oper112Async(float f, long i, string s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Isrv112Channel : WcfClient.ServiceReference2.Isrv112, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Isrv112Client : System.ServiceModel.ClientBase<WcfClient.ServiceReference2.Isrv112>, WcfClient.ServiceReference2.Isrv112 {
        
        public Isrv112Client() {
        }
        
        public Isrv112Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Isrv112Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Isrv112Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Isrv112Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int oper112(float f, long i, string s) {
            return base.Channel.oper112(f, i, s);
        }
        
        public System.Threading.Tasks.Task<int> oper112Async(float f, long i, string s) {
            return base.Channel.oper112Async(f, i, s);
        }
    }
}
