//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IInfo")]
    public interface IInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfo/getInfo", ReplyAction="http://tempuri.org/IInfo/getInfoResponse")]
        string getInfo(string nazwisko, string imie, int iii);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInfo/getInfo", ReplyAction="http://tempuri.org/IInfo/getInfoResponse")]
        System.Threading.Tasks.Task<string> getInfoAsync(string nazwisko, string imie, int iii);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInfoChannel : WcfClient.ServiceReference1.IInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InfoClient : System.ServiceModel.ClientBase<WcfClient.ServiceReference1.IInfo>, WcfClient.ServiceReference1.IInfo {
        
        public InfoClient() {
        }
        
        public InfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getInfo(string nazwisko, string imie, int iii) {
            return base.Channel.getInfo(nazwisko, imie, iii);
        }
        
        public System.Threading.Tasks.Task<string> getInfoAsync(string nazwisko, string imie, int iii) {
            return base.Channel.getInfoAsync(nazwisko, imie, iii);
        }
    }
}
